import { useState } from 'react';
import { useInternetIdentity } from '../hooks/useInternetIdentity';
import { useNavigate } from '@tanstack/react-router';
import DashboardLayout from '../components/DashboardLayout';
import { Brain, BookOpen, HelpCircle, FileText, Calendar, Sparkles, ChevronRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Badge } from '@/components/ui/badge';

const CURRICULA = ['CBSE', 'ICSE', 'IB', 'GCSE', 'SAT', 'IELTS', 'A-Levels', 'AP', 'Common Core'];

// ─── Rule-based AI content generators ────────────────────────────────────────

function generateStudyMaterial(subject: string, curriculum: string): string {
  return `# ${subject} Study Guide — ${curriculum} Curriculum

## Overview
This study guide covers the key concepts of **${subject}** as per the **${curriculum}** curriculum framework.

## Core Topics

### 1. Foundational Concepts
- Understanding the basic principles of ${subject}
- Key terminology and definitions
- Historical context and development

### 2. Core Theory
- Primary theories and models
- Mathematical/analytical frameworks (where applicable)
- Real-world applications

### 3. Advanced Topics
- Complex problem-solving techniques
- Integration with other subjects
- Current developments and research

## Study Tips for ${curriculum}
- Review past papers from the last 5 years
- Focus on examiner reports to understand common mistakes
- Practice timed questions under exam conditions
- Create mind maps for complex topics

## Key Resources
- Official ${curriculum} syllabus documents
- Recommended textbooks for ${subject}
- Online practice platforms
- Study groups and peer learning

## Revision Schedule
| Week | Topics | Practice |
|------|--------|----------|
| 1 | Foundations | 10 questions/day |
| 2 | Core Theory | Past paper sections |
| 3 | Advanced Topics | Full mock papers |
| 4 | Revision | Timed practice |

*Generated by Pristine Learning AI Assistant*`;
}

function generateQuiz(topic: string, curriculum: string): Array<{ question: string; options: string[]; answer: number }> {
  const questions = [
    {
      question: `Which of the following best describes the core principle of ${topic} in ${curriculum}?`,
      options: [
        `The systematic study of ${topic} through empirical methods`,
        `A theoretical framework without practical application`,
        `An outdated concept replaced by modern theories`,
        `A purely mathematical construct`,
      ],
      answer: 0,
    },
    {
      question: `In the ${curriculum} curriculum, ${topic} is primarily assessed through:`,
      options: [
        'Multiple choice questions only',
        'A combination of written exams and coursework',
        'Oral examinations exclusively',
        'Portfolio submissions only',
      ],
      answer: 1,
    },
    {
      question: `Which skill is most important when studying ${topic}?`,
      options: [
        'Memorization of facts without understanding',
        'Critical analysis and application of concepts',
        'Speed reading without comprehension',
        'Copying notes verbatim',
      ],
      answer: 1,
    },
    {
      question: `The ${curriculum} approach to ${topic} emphasizes:`,
      options: [
        'Rote learning and repetition',
        'Conceptual understanding and real-world application',
        'Avoiding practical examples',
        'Focusing only on theoretical aspects',
      ],
      answer: 1,
    },
    {
      question: `A student scoring well in ${topic} under ${curriculum} typically demonstrates:`,
      options: [
        'Only factual recall',
        'Deep conceptual understanding and analytical skills',
        'Ability to copy from textbooks',
        'Speed over accuracy',
      ],
      answer: 1,
    },
  ];
  return questions;
}

function summarizeNotes(text: string): string {
  const sentences = text.split(/[.!?]+/).filter(s => s.trim().length > 20);
  const keyPoints = sentences.slice(0, Math.min(5, Math.ceil(sentences.length * 0.3)));

  return `## Summary

### Key Points
${keyPoints.map((s, i) => `${i + 1}. ${s.trim()}.`).join('\n')}

### Main Themes
- The text covers approximately ${text.split(' ').length} words of content
- ${sentences.length} key statements identified
- Core concepts have been extracted above

### Study Recommendation
Review the key points above and create flashcards for each main concept. Focus on understanding the relationships between ideas rather than memorizing individual facts.

*Summarized by Pristine Learning AI Assistant*`;
}

function generateStudyPlan(goals: string, subject: string, curriculum: string): string {
  return `# Personalized Study Plan
**Subject:** ${subject} | **Curriculum:** ${curriculum}
**Goal:** ${goals}

## 8-Week Study Plan

### Week 1–2: Foundation Building
- **Monday/Wednesday/Friday:** Core concept review (45 min each)
- **Tuesday/Thursday:** Practice problems (30 min each)
- **Weekend:** Review and consolidate (1 hour)
- Focus: Chapters 1–3, basic terminology

### Week 3–4: Core Development
- **Daily:** Topic-specific study (1 hour)
- **Weekend:** Past paper practice (2 hours)
- Focus: Main theories and applications

### Week 5–6: Advanced Topics
- **Daily:** Complex problem solving (1 hour)
- **Weekend:** Full mock exam (3 hours)
- Focus: Higher-order thinking skills

### Week 7: Intensive Revision
- **Daily:** Targeted weak areas (2 hours)
- Review all previous notes
- Focus: Exam technique and timing

### Week 8: Final Preparation
- **Daily:** Light revision (45 min)
- Rest and mental preparation
- Focus: Confidence building

## Daily Study Tips
✅ Start each session with a 5-minute review of previous material
✅ Use the Pomodoro technique: 25 min study, 5 min break
✅ End each session by writing 3 key takeaways
✅ Stay hydrated and take regular breaks

## Progress Milestones
- [ ] Week 2: Complete foundation topics
- [ ] Week 4: Score 60%+ on practice tests
- [ ] Week 6: Score 75%+ on mock exams
- [ ] Week 8: Achieve target grade

*Generated by Pristine Learning AI Assistant*`;
}

// ─── Tool Components ──────────────────────────────────────────────────────────

function StudyMaterialTool() {
  const [subject, setSubject] = useState('');
  const [curriculum, setCurriculum] = useState('');
  const [result, setResult] = useState('');
  const [loading, setLoading] = useState(false);

  const handleGenerate = () => {
    if (!subject || !curriculum) return;
    setLoading(true);
    setTimeout(() => {
      setResult(generateStudyMaterial(subject, curriculum));
      setLoading(false);
    }, 800);
  };

  return (
    <div className="space-y-4">
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
        <div className="space-y-1">
          <Label>Subject</Label>
          <Input placeholder="e.g. Mathematics, Physics…" value={subject} onChange={e => setSubject(e.target.value)} />
        </div>
        <div className="space-y-1">
          <Label>Curriculum</Label>
          <Select value={curriculum} onValueChange={setCurriculum}>
            <SelectTrigger><SelectValue placeholder="Select curriculum" /></SelectTrigger>
            <SelectContent>
              {CURRICULA.map(c => <SelectItem key={c} value={c}>{c}</SelectItem>)}
            </SelectContent>
          </Select>
        </div>
      </div>
      <Button onClick={handleGenerate} disabled={!subject || !curriculum || loading} className="btn-primary gap-2">
        <Sparkles className="w-4 h-4" />
        {loading ? 'Generating…' : 'Generate Study Material'}
      </Button>
      {result && (
        <div className="bg-muted/30 rounded-xl p-5 border border-border">
          <pre className="whitespace-pre-wrap text-sm font-sans leading-relaxed">{result}</pre>
        </div>
      )}
    </div>
  );
}

function QuizTool() {
  const [topic, setTopic] = useState('');
  const [curriculum, setCurriculum] = useState('');
  const [questions, setQuestions] = useState<Array<{ question: string; options: string[]; answer: number }>>([]);
  const [selected, setSelected] = useState<Record<number, number>>({});
  const [submitted, setSubmitted] = useState(false);
  const [loading, setLoading] = useState(false);

  const handleGenerate = () => {
    if (!topic || !curriculum) return;
    setLoading(true);
    setSelected({});
    setSubmitted(false);
    setTimeout(() => {
      setQuestions(generateQuiz(topic, curriculum));
      setLoading(false);
    }, 600);
  };

  const score = submitted
    ? questions.filter((q, i) => selected[i] === q.answer).length
    : 0;

  return (
    <div className="space-y-4">
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
        <div className="space-y-1">
          <Label>Topic</Label>
          <Input placeholder="e.g. Algebra, Photosynthesis…" value={topic} onChange={e => setTopic(e.target.value)} />
        </div>
        <div className="space-y-1">
          <Label>Curriculum</Label>
          <Select value={curriculum} onValueChange={setCurriculum}>
            <SelectTrigger><SelectValue placeholder="Select curriculum" /></SelectTrigger>
            <SelectContent>
              {CURRICULA.map(c => <SelectItem key={c} value={c}>{c}</SelectItem>)}
            </SelectContent>
          </Select>
        </div>
      </div>
      <Button onClick={handleGenerate} disabled={!topic || !curriculum || loading} className="btn-primary gap-2">
        <HelpCircle className="w-4 h-4" />
        {loading ? 'Generating…' : 'Generate Quiz'}
      </Button>

      {questions.length > 0 && (
        <div className="space-y-4">
          {submitted && (
            <div className={`p-4 rounded-xl border ${score >= 4 ? 'bg-green-50 border-green-200' : 'bg-amber-50 border-amber-200'}`}>
              <p className="font-semibold">Score: {score}/{questions.length}</p>
              <p className="text-sm text-muted-foreground">
                {score >= 4 ? '🎉 Excellent work!' : score >= 3 ? '👍 Good effort!' : '📚 Keep studying!'}
              </p>
            </div>
          )}
          {questions.map((q, qi) => (
            <div key={qi} className="bg-white rounded-xl border border-border p-4">
              <p className="font-medium text-sm mb-3">{qi + 1}. {q.question}</p>
              <div className="space-y-2">
                {q.options.map((opt, oi) => (
                  <button
                    key={oi}
                    onClick={() => !submitted && setSelected(prev => ({ ...prev, [qi]: oi }))}
                    className={`w-full text-left px-3 py-2 rounded-lg border text-sm transition-all ${
                      submitted
                        ? oi === q.answer
                          ? 'bg-green-50 border-green-400 text-green-700'
                          : selected[qi] === oi
                          ? 'bg-red-50 border-red-300 text-red-600'
                          : 'border-border'
                        : selected[qi] === oi
                        ? 'border-primary bg-primary/5 text-primary'
                        : 'border-border hover:border-primary/40'
                    }`}
                  >
                    {String.fromCharCode(65 + oi)}. {opt}
                  </button>
                ))}
              </div>
            </div>
          ))}
          {!submitted && (
            <Button
              onClick={() => setSubmitted(true)}
              disabled={Object.keys(selected).length < questions.length}
              className="btn-primary"
            >
              Submit Answers
            </Button>
          )}
          {submitted && (
            <Button variant="outline" onClick={() => { setSubmitted(false); setSelected({}); setQuestions([]); }}>
              Try Another Quiz
            </Button>
          )}
        </div>
      )}
    </div>
  );
}

function NoteSummarizerTool() {
  const [notes, setNotes] = useState('');
  const [summary, setSummary] = useState('');
  const [loading, setLoading] = useState(false);

  const handleSummarize = () => {
    if (!notes.trim()) return;
    setLoading(true);
    setTimeout(() => {
      setSummary(summarizeNotes(notes));
      setLoading(false);
    }, 600);
  };

  return (
    <div className="space-y-4">
      <div className="space-y-1">
        <Label>Paste Your Notes</Label>
        <Textarea
          placeholder="Paste your notes here to get a concise summary…"
          value={notes}
          onChange={e => setNotes(e.target.value)}
          rows={8}
          className="font-mono text-sm"
        />
        <p className="text-xs text-muted-foreground">{notes.split(' ').filter(Boolean).length} words</p>
      </div>
      <Button onClick={handleSummarize} disabled={!notes.trim() || loading} className="btn-primary gap-2">
        <FileText className="w-4 h-4" />
        {loading ? 'Summarizing…' : 'Summarize Notes'}
      </Button>
      {summary && (
        <div className="bg-muted/30 rounded-xl p-5 border border-border">
          <pre className="whitespace-pre-wrap text-sm font-sans leading-relaxed">{summary}</pre>
        </div>
      )}
    </div>
  );
}

function StudyPlanTool() {
  const [goals, setGoals] = useState('');
  const [subject, setSubject] = useState('');
  const [curriculum, setCurriculum] = useState('');
  const [plan, setPlan] = useState('');
  const [loading, setLoading] = useState(false);

  const handleGenerate = () => {
    if (!goals || !subject || !curriculum) return;
    setLoading(true);
    setTimeout(() => {
      setPlan(generateStudyPlan(goals, subject, curriculum));
      setLoading(false);
    }, 800);
  };

  return (
    <div className="space-y-4">
      <div className="space-y-1">
        <Label>Your Goals</Label>
        <Input
          placeholder="e.g. Score 90%+ in IB Math HL exam in 3 months"
          value={goals}
          onChange={e => setGoals(e.target.value)}
        />
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
        <div className="space-y-1">
          <Label>Subject</Label>
          <Input placeholder="e.g. Mathematics" value={subject} onChange={e => setSubject(e.target.value)} />
        </div>
        <div className="space-y-1">
          <Label>Curriculum</Label>
          <Select value={curriculum} onValueChange={setCurriculum}>
            <SelectTrigger><SelectValue placeholder="Select curriculum" /></SelectTrigger>
            <SelectContent>
              {CURRICULA.map(c => <SelectItem key={c} value={c}>{c}</SelectItem>)}
            </SelectContent>
          </Select>
        </div>
      </div>
      <Button onClick={handleGenerate} disabled={!goals || !subject || !curriculum || loading} className="btn-primary gap-2">
        <Calendar className="w-4 h-4" />
        {loading ? 'Generating…' : 'Generate Study Plan'}
      </Button>
      {plan && (
        <div className="bg-muted/30 rounded-xl p-5 border border-border">
          <pre className="whitespace-pre-wrap text-sm font-sans leading-relaxed">{plan}</pre>
        </div>
      )}
    </div>
  );
}

// ─── Main Page ────────────────────────────────────────────────────────────────

export default function AIStudyAssistantPage() {
  const { identity } = useInternetIdentity();
  const navigate = useNavigate();

  if (!identity) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background">
        <div className="text-center">
          <h2 className="font-display text-2xl font-bold mb-3">Login Required</h2>
          <Button onClick={() => navigate({ to: '/' })} className="btn-primary">Go to Homepage</Button>
        </div>
      </div>
    );
  }

  return (
    <DashboardLayout role="student">
      <div className="p-6 space-y-6 animate-fade-in">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 bg-primary/10 rounded-xl flex items-center justify-center">
            <Brain className="w-6 h-6 text-primary" />
          </div>
          <div>
            <h1 className="font-display text-2xl font-bold">AI Study Assistant</h1>
            <p className="text-muted-foreground text-sm">Powered by intelligent content generation for all major curricula</p>
          </div>
        </div>

        <div className="flex flex-wrap gap-2">
          {CURRICULA.map(c => (
            <Badge key={c} variant="secondary" className="text-xs">{c}</Badge>
          ))}
        </div>

        <Tabs defaultValue="materials">
          <TabsList className="flex-wrap h-auto gap-1">
            <TabsTrigger value="materials" className="gap-1.5">
              <BookOpen className="w-3.5 h-3.5" /> Study Materials
            </TabsTrigger>
            <TabsTrigger value="quiz" className="gap-1.5">
              <HelpCircle className="w-3.5 h-3.5" /> Quiz Creator
            </TabsTrigger>
            <TabsTrigger value="summarize" className="gap-1.5">
              <FileText className="w-3.5 h-3.5" /> Note Summarizer
            </TabsTrigger>
            <TabsTrigger value="plan" className="gap-1.5">
              <Calendar className="w-3.5 h-3.5" /> Study Plan
            </TabsTrigger>
          </TabsList>

          <TabsContent value="materials" className="mt-4">
            <div className="bg-white rounded-xl border border-border p-6">
              <h2 className="font-semibold mb-1">Study Material Generator</h2>
              <p className="text-sm text-muted-foreground mb-4">
                Generate comprehensive study notes for any subject and curriculum.
              </p>
              <StudyMaterialTool />
            </div>
          </TabsContent>

          <TabsContent value="quiz" className="mt-4">
            <div className="bg-white rounded-xl border border-border p-6">
              <h2 className="font-semibold mb-1">Quiz Creator</h2>
              <p className="text-sm text-muted-foreground mb-4">
                Generate multiple-choice quizzes to test your knowledge.
              </p>
              <QuizTool />
            </div>
          </TabsContent>

          <TabsContent value="summarize" className="mt-4">
            <div className="bg-white rounded-xl border border-border p-6">
              <h2 className="font-semibold mb-1">Note Summarizer</h2>
              <p className="text-sm text-muted-foreground mb-4">
                Paste your notes and get a concise, structured summary.
              </p>
              <NoteSummarizerTool />
            </div>
          </TabsContent>

          <TabsContent value="plan" className="mt-4">
            <div className="bg-white rounded-xl border border-border p-6">
              <h2 className="font-semibold mb-1">Personalized Study Plan</h2>
              <p className="text-sm text-muted-foreground mb-4">
                Get a customized weekly study plan based on your goals.
              </p>
              <StudyPlanTool />
            </div>
          </TabsContent>
        </Tabs>
      </div>
    </DashboardLayout>
  );
}
