import { useState } from 'react';
import { useInternetIdentity } from '../hooks/useInternetIdentity';
import { useNavigate } from '@tanstack/react-router';
import DashboardLayout from '../components/DashboardLayout';
import { Brain, BookOpen, HelpCircle, FileText, Calendar, Sparkles, ChevronRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Badge } from '@/components/ui/badge';

const CURRICULA = [
  'CBSE',
  'ICSE',
  'Tamil Nadu Samacheer Kalvi',
  'IB',
  'GCSE',
  'SAT',
  'IELTS',
  'A-Levels',
  'AP',
  'Common Core',
];

// ─── TN Samacheer Kalvi subject-specific content maps ─────────────────────────

const TN_STUDY_MATERIALS: Record<string, string> = {
  Mathematics: `# Mathematics Study Guide — Tamil Nadu Samacheer Kalvi

## Overview
This guide covers **Mathematics** as per the **Tamil Nadu Samacheer Kalvi** State Board syllabus (Classes 6–12), aligned with the Tamil Nadu School Education Department framework.

## Class-wise Core Topics

### Classes 6–8: Foundation
- **Numbers & Operations:** Natural numbers, integers, fractions, decimals, rational numbers
- **Algebra:** Introduction to variables, simple equations, algebraic expressions
- **Geometry:** Lines, angles, triangles, quadrilaterals, circles — properties and constructions
- **Mensuration:** Perimeter, area of 2D shapes; surface area and volume of 3D solids
- **Statistics:** Data collection, bar graphs, pie charts, mean, median, mode

### Classes 9–10: Core
- **Real Numbers & Polynomials:** Euclid's division lemma, HCF, LCM, polynomial operations
- **Algebra:** Linear equations in two variables, quadratic equations, arithmetic progressions
- **Coordinate Geometry:** Distance formula, section formula, area of triangle
- **Trigonometry:** Ratios, identities, heights and distances
- **Geometry:** Similar triangles, Pythagoras theorem, circles and tangents
- **Statistics & Probability:** Cumulative frequency, ogive, probability basics

### Classes 11–12: Advanced
- **Sets, Relations & Functions:** Types of functions, inverse functions
- **Algebra:** Matrices, determinants, complex numbers, sequences and series
- **Calculus:** Limits, differentiation, integration, applications
- **Probability:** Conditional probability, Bayes' theorem, distributions
- **Vector Algebra & 3D Geometry** (Class 12)

## Samacheer Kalvi Exam Tips
- Solve all **Textbook Exercise** problems — questions are directly from them
- Practice **Example Problems** in each chapter
- Focus on **2-mark, 5-mark, and 8-mark** question patterns
- Use the official **Samacheer Kalvi textbooks** (available free on textbooks.esb.tn.gov.in)
- Refer to **Sura's / Navneet / Guide** publications for additional practice

## Revision Schedule
| Week | Topics | Practice |
|------|--------|----------|
| 1 | Numbers, Algebra basics | 15 textbook problems/day |
| 2 | Geometry & Mensuration | Past public exam questions |
| 3 | Trigonometry & Coordinate Geometry | Full chapter exercises |
| 4 | Statistics, Probability & Revision | Model question papers |

*Generated by Pristine Learning AI Assistant — Tamil Nadu Samacheer Kalvi*`,

  Science: `# Science Study Guide — Tamil Nadu Samacheer Kalvi

## Overview
This guide covers **Science** as per the **Tamil Nadu Samacheer Kalvi** State Board syllabus, integrating Physics, Chemistry, and Biology as per the unified Science curriculum for Classes 6–10 and separate streams for Classes 11–12.

## Class-wise Core Topics

### Classes 6–8: Integrated Science
- **Physics:** Force, motion, light, sound, electricity, magnetism
- **Chemistry:** Matter, elements, compounds, mixtures, acids, bases, salts
- **Biology:** Cell structure, plant kingdom, animal kingdom, human body systems, nutrition

### Classes 9–10: Core Science
- **Physics:** Laws of motion, gravitation, work and energy, optics, electricity, electromagnetism
- **Chemistry:** Atomic structure, periodic table, chemical bonding, carbon compounds, metallurgy
- **Biology:** Cell division, genetics, evolution, plant physiology, human physiology, ecology

### Classes 11–12: Separate Streams
**Physics:** Mechanics, thermodynamics, waves, optics, electrostatics, current electricity, modern physics
**Chemistry:** Atomic structure, chemical equilibrium, electrochemistry, organic chemistry, biomolecules
**Biology:** Cell biology, genetics, biotechnology, ecology, human physiology, plant physiology

## Samacheer Kalvi Exam Tips
- Learn all **diagrams** with proper labelling (carries significant marks)
- Memorize **definitions** and **laws** word-for-word from the textbook
- Practice **numerical problems** in Physics and Chemistry
- Understand **life processes** diagrams for Biology
- Refer to **TNPSC Group** materials for additional conceptual clarity

## Key Chapters (Class 10 — High Weightage)
- Laws of Motion & Gravitation
- Optics
- Atomic Structure
- Periodic Classification
- Plant and Animal Hormones
- Genetics

*Generated by Pristine Learning AI Assistant — Tamil Nadu Samacheer Kalvi*`,

  'Social Science': `# Social Science Study Guide — Tamil Nadu Samacheer Kalvi

## Overview
This guide covers **Social Science** as per the **Tamil Nadu Samacheer Kalvi** State Board syllabus, encompassing History, Geography, Civics, and Economics for Classes 6–10.

## Core Topics by Strand

### History
- **Ancient Tamil Nadu:** Sangam Age, Pallava, Chola, Pandya, Chera dynasties
- **Medieval India:** Delhi Sultanate, Mughal Empire, Vijayanagara Empire
- **Modern India:** British colonialism, Indian National Movement, role of Tamil leaders
- **Post-Independence:** Constitution, Five-Year Plans, India's development

### Geography
- **Physical Geography:** Earth's structure, landforms, rivers, climate zones
- **Tamil Nadu Geography:** Districts, rivers (Cauvery, Vaigai, Tamiraparani), natural resources
- **India's Geography:** Physiographic divisions, monsoon, agriculture, industries
- **World Geography:** Continents, oceans, climate, population

### Civics / Political Science
- **Indian Constitution:** Preamble, Fundamental Rights, Directive Principles
- **Government Structure:** Parliament, State Legislature, Judiciary
- **Local Self-Government:** Panchayati Raj, Urban Local Bodies
- **Tamil Nadu Administration:** Districts, Collectors, Gram Panchayats

### Economics
- **Basic Concepts:** Needs, wants, production, consumption, distribution
- **Indian Economy:** Agriculture, industries, services sector
- **Banking & Finance:** RBI, commercial banks, cooperative banks
- **Development Indicators:** GDP, HDI, poverty, unemployment

## Samacheer Kalvi Exam Tips
- Learn **map-based questions** — mark rivers, states, capitals
- Memorize **important dates** in Indian and Tamil history
- Understand **constitutional articles** and their significance
- Practice **5-mark and 8-mark** essay-type answers

*Generated by Pristine Learning AI Assistant — Tamil Nadu Samacheer Kalvi*`,

  English: `# English Study Guide — Tamil Nadu Samacheer Kalvi

## Overview
This guide covers **English** as per the **Tamil Nadu Samacheer Kalvi** State Board syllabus, focusing on language skills, literature, and grammar for Classes 6–12.

## Core Components

### Reading Comprehension
- Unseen passages with factual and inferential questions
- Identifying main idea, supporting details, tone, and purpose
- Vocabulary in context — synonyms, antonyms, word meanings

### Grammar (High Weightage)
- **Parts of Speech:** Nouns, pronouns, verbs, adjectives, adverbs, prepositions, conjunctions
- **Tenses:** Simple, continuous, perfect, perfect continuous — active and passive voice
- **Sentence Transformation:** Direct/indirect speech, degrees of comparison, combining sentences
- **Punctuation & Spelling**
- **Phrasal Verbs & Idioms**

### Writing Skills
- **Formal Letter Writing:** Complaint, request, application letters
- **Essay Writing:** Descriptive, narrative, argumentative essays
- **Paragraph Writing & Précis Writing**
- **Notice, Advertisement, and Report Writing**

### Literature (Prose & Poetry)
- Prescribed prose lessons from the Samacheer Kalvi textbook
- Poems with appreciation questions (rhyme scheme, figures of speech, theme)
- Supplementary reader stories

## Samacheer Kalvi Exam Tips
- Practice **letter writing formats** — marks are given for format
- Learn **grammar rules** with examples from the textbook
- Read all **prescribed prose and poetry** carefully
- Attempt **creative writing** sections with proper structure
- Build vocabulary using the **glossary** in each lesson

*Generated by Pristine Learning AI Assistant — Tamil Nadu Samacheer Kalvi*`,
};

const TN_DEFAULT_STUDY_MATERIAL = (subject: string) => `# ${subject} Study Guide — Tamil Nadu Samacheer Kalvi

## Overview
This study guide covers **${subject}** as per the **Tamil Nadu Samacheer Kalvi** State Board syllabus, aligned with the Tamil Nadu School Education Department framework for Classes 6–12.

## Core Topics

### Foundation Level (Classes 6–8)
- Introduction to ${subject} — basic concepts and terminology
- Foundational principles as outlined in the Samacheer Kalvi textbook
- Activity-based learning and practical applications

### Intermediate Level (Classes 9–10)
- Core theories and models in ${subject}
- Problem-solving techniques and analytical methods
- Application to real-world Tamil Nadu context
- Public Examination preparation (Chapter-wise exercises)

### Advanced Level (Classes 11–12)
- In-depth study of ${subject} concepts
- Higher-order thinking and application questions
- Board exam pattern: 1-mark, 2-mark, 3-mark, 5-mark questions

## Samacheer Kalvi Exam Tips
- Solve all **Textbook Exercise** problems thoroughly
- Focus on **Example Problems** in each chapter
- Practice **Model Question Papers** from the Tamil Nadu Board
- Use official **Samacheer Kalvi textbooks** (free at textbooks.esb.tn.gov.in)
- Refer to **Sura's / Navneet** guides for additional practice

## Revision Schedule
| Week | Topics | Practice |
|------|--------|----------|
| 1 | Chapters 1–3 (Foundation) | 10 textbook problems/day |
| 2 | Chapters 4–6 (Core) | Past public exam questions |
| 3 | Chapters 7–9 (Advanced) | Full chapter exercises |
| 4 | Revision | Model question papers |

*Generated by Pristine Learning AI Assistant — Tamil Nadu Samacheer Kalvi*`;

// ─── TN Samacheer Kalvi quiz templates ───────────────────────────────────────

const TN_QUIZ_TEMPLATES: Record<string, Array<{ question: string; options: string[]; answer: number }>> = {
  Mathematics: [
    {
      question: 'In the Tamil Nadu Samacheer Kalvi Class 10 syllabus, which theorem states that in a right-angled triangle, the square of the hypotenuse equals the sum of squares of the other two sides?',
      options: ['Thales\' Theorem', 'Pythagoras\' Theorem', 'Euclid\'s Theorem', 'Angle Bisector Theorem'],
      answer: 1,
    },
    {
      question: 'According to the Samacheer Kalvi syllabus, the standard form of a quadratic equation is:',
      options: ['ax + b = 0', 'ax² + bx + c = 0', 'ax³ + bx² + cx + d = 0', 'a/x + b = 0'],
      answer: 1,
    },
    {
      question: 'In the Samacheer Kalvi Class 9 curriculum, the distance between two points (x₁, y₁) and (x₂, y₂) is given by:',
      options: [
        '(x₂ - x₁) + (y₂ - y₁)',
        '√[(x₂ - x₁)² + (y₂ - y₁)²]',
        '(x₂ + x₁) × (y₂ + y₁)',
        '|x₂ - x₁| × |y₂ - y₁|',
      ],
      answer: 1,
    },
    {
      question: 'The Samacheer Kalvi Class 10 syllabus covers trigonometric ratios. What is the value of sin 30°?',
      options: ['1', '√3/2', '1/2', '1/√2'],
      answer: 2,
    },
    {
      question: 'In the Tamil Nadu Samacheer Kalvi public exam pattern, the highest mark question type is typically:',
      options: ['1-mark MCQ', '2-mark short answer', '5-mark answer', '8-mark long answer'],
      answer: 3,
    },
  ],
  Science: [
    {
      question: 'According to the Samacheer Kalvi Class 10 Science syllabus, Newton\'s First Law of Motion is also known as:',
      options: ['Law of Acceleration', 'Law of Inertia', 'Law of Action-Reaction', 'Law of Gravitation'],
      answer: 1,
    },
    {
      question: 'In the Samacheer Kalvi Biology curriculum, which organelle is called the "powerhouse of the cell"?',
      options: ['Nucleus', 'Ribosome', 'Mitochondria', 'Golgi apparatus'],
      answer: 2,
    },
    {
      question: 'The Samacheer Kalvi Class 9 Chemistry syllabus covers the periodic table. Which scientist arranged elements by atomic number?',
      options: ['Mendeleev', 'Moseley', 'Newlands', 'Dobereiner'],
      answer: 1,
    },
    {
      question: 'In the Tamil Nadu Samacheer Kalvi Class 10 syllabus, the process by which plants make food using sunlight is called:',
      options: ['Respiration', 'Transpiration', 'Photosynthesis', 'Digestion'],
      answer: 2,
    },
    {
      question: 'According to the Samacheer Kalvi Science curriculum, which acid is present in the human stomach?',
      options: ['Sulphuric acid', 'Nitric acid', 'Hydrochloric acid', 'Acetic acid'],
      answer: 2,
    },
  ],
  'Social Science': [
    {
      question: 'The Samacheer Kalvi History syllabus covers the Chola dynasty. Which Chola king is famous for his naval expeditions to Southeast Asia?',
      options: ['Rajaraja Chola I', 'Rajendra Chola I', 'Kulottunga Chola', 'Parantaka Chola'],
      answer: 1,
    },
    {
      question: 'According to the Samacheer Kalvi Geography syllabus, which is the longest river in Tamil Nadu?',
      options: ['Vaigai', 'Tamiraparani', 'Cauvery', 'Palar'],
      answer: 2,
    },
    {
      question: 'In the Samacheer Kalvi Civics curriculum, the Preamble to the Indian Constitution begins with:',
      options: ['"We the People of India"', '"In the name of God"', '"The Government of India"', '"By the authority of Parliament"'],
      answer: 0,
    },
    {
      question: 'The Samacheer Kalvi syllabus covers the Indian National Movement. Who is known as the "Father of the Nation"?',
      options: ['Jawaharlal Nehru', 'Subhas Chandra Bose', 'Mahatma Gandhi', 'Bal Gangadhar Tilak'],
      answer: 2,
    },
    {
      question: 'According to the Samacheer Kalvi Economics curriculum, which institution is the central bank of India?',
      options: ['State Bank of India', 'Reserve Bank of India', 'NABARD', 'SEBI'],
      answer: 1,
    },
  ],
  English: [
    {
      question: 'In the Samacheer Kalvi English grammar syllabus, which of the following is an example of a compound sentence?',
      options: [
        'She went to school.',
        'She went to school and she studied hard.',
        'Because she studied hard, she passed.',
        'She, who studied hard, passed.',
      ],
      answer: 1,
    },
    {
      question: 'The Samacheer Kalvi English syllabus emphasizes letter writing. Which format is used for a formal complaint letter?',
      options: [
        'Informal greeting, body, casual closing',
        'Sender\'s address, date, receiver\'s address, subject, body, formal closing',
        'Only body paragraphs without address',
        'Email format with CC and BCC',
      ],
      answer: 1,
    },
    {
      question: 'In the Samacheer Kalvi English curriculum, "Direct Speech" converted to "Indirect Speech" requires changing:',
      options: [
        'Only the punctuation',
        'Only the verb tense',
        'Pronouns, verb tense, and reporting verb',
        'Only the subject',
      ],
      answer: 2,
    },
    {
      question: 'According to the Samacheer Kalvi syllabus, a "précis" is:',
      options: [
        'A detailed expansion of a passage',
        'A condensed version of a passage retaining the main ideas',
        'A creative story based on a passage',
        'A word-for-word copy of a passage',
      ],
      answer: 1,
    },
    {
      question: 'In the Samacheer Kalvi English grammar, the passive voice of "She writes a letter" is:',
      options: [
        'A letter is being written by her.',
        'A letter was written by her.',
        'A letter is written by her.',
        'A letter will be written by her.',
      ],
      answer: 2,
    },
  ],
};

function getTNQuiz(topic: string): Array<{ question: string; options: string[]; answer: number }> {
  const key = Object.keys(TN_QUIZ_TEMPLATES).find(k => topic.toLowerCase().includes(k.toLowerCase()));
  if (key) return TN_QUIZ_TEMPLATES[key];
  // Generic TN Samacheer fallback
  return [
    {
      question: `In the Tamil Nadu Samacheer Kalvi syllabus, ${topic} is primarily taught through:`,
      options: [
        'Rote memorisation only',
        'Activity-based learning and textbook exercises',
        'Online-only resources',
        'No structured curriculum',
      ],
      answer: 1,
    },
    {
      question: `The Samacheer Kalvi public exam for ${topic} includes which question types?`,
      options: [
        'Only multiple choice questions',
        '1-mark, 2-mark, 5-mark, and 8-mark questions',
        'Only essay questions',
        'Only practical exams',
      ],
      answer: 1,
    },
    {
      question: `Official Samacheer Kalvi textbooks for ${topic} are published by:`,
      options: [
        'NCERT',
        'Tamil Nadu Textbook and Educational Services Corporation (TNTESC)',
        'CBSE Board',
        'Private publishers only',
      ],
      answer: 1,
    },
    {
      question: `In the Tamil Nadu Samacheer Kalvi framework, the medium of instruction for ${topic} can be:`,
      options: [
        'English only',
        'Tamil only',
        'Tamil or English (student\'s choice)',
        'Hindi only',
      ],
      answer: 2,
    },
    {
      question: `The Samacheer Kalvi curriculum for ${topic} is designed to align with:`,
      options: [
        'International Baccalaureate standards',
        'National Curriculum Framework (NCF) and Tamil Nadu state guidelines',
        'Cambridge IGCSE standards',
        'American Common Core standards',
      ],
      answer: 1,
    },
  ];
}

// ─── TN Samacheer Kalvi study plan template ───────────────────────────────────

function getTNStudyPlan(goals: string, subject: string): string {
  const subjectKey = Object.keys(TN_STUDY_MATERIALS).find(k => subject.toLowerCase().includes(k.toLowerCase()));
  const chapterHints: Record<string, string> = {
    Mathematics: 'Numbers, Algebra, Geometry, Trigonometry, Statistics',
    Science: 'Physics (Motion, Optics), Chemistry (Periodic Table, Carbon), Biology (Cell, Genetics)',
    'Social Science': 'History (Chola, Mughal, Freedom Movement), Geography (Tamil Nadu, India), Civics, Economics',
    English: 'Grammar (Tenses, Voice, Speech), Writing (Letters, Essays), Literature (Prose, Poetry)',
  };
  const chapters = subjectKey ? chapterHints[subjectKey] : 'Core chapters as per the Samacheer Kalvi textbook';

  return `# Personalized Study Plan — Tamil Nadu Samacheer Kalvi
**Subject:** ${subject} | **Curriculum:** Tamil Nadu Samacheer Kalvi State Board
**Goal:** ${goals}

## Key Topics to Cover
${chapters}

## 8-Week Samacheer Kalvi Study Plan

### Week 1–2: Textbook Foundation
- **Monday/Wednesday/Friday:** Read and understand textbook chapters (45 min each)
- **Tuesday/Thursday:** Solve all in-text examples and exercises (30 min each)
- **Weekend:** Review chapter summaries and key definitions (1 hour)
- Focus: Chapters 1–3, basic terminology and definitions

### Week 3–4: Exercise Practice
- **Daily:** Solve textbook exercise problems (1 hour)
- **Weekend:** Attempt previous year public exam questions (2 hours)
- Focus: 2-mark and 5-mark question patterns

### Week 5–6: Model Papers & Mock Tests
- **Daily:** Topic-specific practice from Sura's / Navneet guide (1 hour)
- **Weekend:** Full model question paper under timed conditions (3 hours)
- Focus: 8-mark long answer questions and diagram-based questions

### Week 7: Targeted Revision
- **Daily:** Revisit weak chapters (2 hours)
- Review all important formulas, definitions, and diagrams
- Focus: High-weightage chapters identified from past papers

### Week 8: Final Preparation
- **Daily:** Light revision and confidence building (45 min)
- Solve the official Tamil Nadu Board model question paper
- Focus: Exam technique, time management, and presentation

## Samacheer Kalvi Exam Strategy
✅ Always write answers in the format expected by the board (structured paragraphs)
✅ Draw and label diagrams wherever applicable — they carry separate marks
✅ Memorize key definitions word-for-word from the textbook
✅ Practice the Pomodoro technique: 25 min study, 5 min break
✅ Download free textbooks from **textbooks.esb.tn.gov.in**

## Progress Milestones
- [ ] Week 2: Complete all textbook exercises for foundation chapters
- [ ] Week 4: Score 60%+ on practice question sets
- [ ] Week 6: Score 75%+ on full model question papers
- [ ] Week 8: Achieve target grade in the Tamil Nadu Board exam

*Generated by Pristine Learning AI Assistant — Tamil Nadu Samacheer Kalvi*`;
}

// ─── Rule-based AI content generators ────────────────────────────────────────

function generateStudyMaterial(subject: string, curriculum: string): string {
  if (curriculum === 'Tamil Nadu Samacheer Kalvi') {
    const key = Object.keys(TN_STUDY_MATERIALS).find(k => subject.toLowerCase().includes(k.toLowerCase()));
    if (key) return TN_STUDY_MATERIALS[key];
    return TN_DEFAULT_STUDY_MATERIAL(subject);
  }

  return `# ${subject} Study Guide — ${curriculum} Curriculum

## Overview
This study guide covers the key concepts of **${subject}** as per the **${curriculum}** curriculum framework.

## Core Topics

### 1. Foundational Concepts
- Understanding the basic principles of ${subject}
- Key terminology and definitions
- Historical context and development

### 2. Core Theory
- Primary theories and models
- Mathematical/analytical frameworks (where applicable)
- Real-world applications

### 3. Advanced Topics
- Complex problem-solving techniques
- Integration with other subjects
- Current developments and research

## Study Tips for ${curriculum}
- Review past papers from the last 5 years
- Focus on examiner reports to understand common mistakes
- Practice timed questions under exam conditions
- Create mind maps for complex topics

## Key Resources
- Official ${curriculum} syllabus documents
- Recommended textbooks for ${subject}
- Online practice platforms
- Study groups and peer learning

## Revision Schedule
| Week | Topics | Practice |
|------|--------|----------|
| 1 | Foundations | 10 questions/day |
| 2 | Core Theory | Past paper sections |
| 3 | Advanced Topics | Full mock papers |
| 4 | Revision | Timed practice |

*Generated by Pristine Learning AI Assistant*`;
}

function generateQuiz(topic: string, curriculum: string): Array<{ question: string; options: string[]; answer: number }> {
  if (curriculum === 'Tamil Nadu Samacheer Kalvi') {
    return getTNQuiz(topic);
  }

  const questions = [
    {
      question: `Which of the following best describes the core principle of ${topic} in ${curriculum}?`,
      options: [
        `The systematic study of ${topic} through empirical methods`,
        `A theoretical framework without practical application`,
        `An outdated concept replaced by modern theories`,
        `A purely mathematical construct`,
      ],
      answer: 0,
    },
    {
      question: `In the ${curriculum} curriculum, ${topic} is primarily assessed through:`,
      options: [
        'Multiple choice questions only',
        'A combination of written exams and coursework',
        'Oral examinations exclusively',
        'Portfolio submissions only',
      ],
      answer: 1,
    },
    {
      question: `Which skill is most important when studying ${topic}?`,
      options: [
        'Memorization of facts without understanding',
        'Critical analysis and application of concepts',
        'Speed reading without comprehension',
        'Copying notes verbatim',
      ],
      answer: 1,
    },
    {
      question: `The ${curriculum} approach to ${topic} emphasizes:`,
      options: [
        'Rote learning and repetition',
        'Conceptual understanding and real-world application',
        'Avoiding practical examples',
        'Focusing only on theoretical aspects',
      ],
      answer: 1,
    },
    {
      question: `A student scoring well in ${topic} under ${curriculum} typically demonstrates:`,
      options: [
        'Only factual recall',
        'Deep conceptual understanding and analytical skills',
        'Ability to copy from textbooks',
        'Speed over accuracy',
      ],
      answer: 1,
    },
  ];
  return questions;
}

function summarizeNotes(text: string): string {
  const sentences = text.split(/[.!?]+/).filter(s => s.trim().length > 20);
  const keyPoints = sentences.slice(0, Math.min(5, Math.ceil(sentences.length * 0.3)));

  return `## Summary

### Key Points
${keyPoints.map((s, i) => `${i + 1}. ${s.trim()}.`).join('\n')}

### Main Themes
- The text covers approximately ${text.split(' ').length} words of content
- ${sentences.length} key statements identified
- Core concepts have been extracted above

### Study Recommendation
Review the key points above and create flashcards for each main concept. Focus on understanding the relationships between ideas rather than memorizing individual facts.

*Summarized by Pristine Learning AI Assistant*`;
}

function generateStudyPlan(goals: string, subject: string, curriculum: string): string {
  if (curriculum === 'Tamil Nadu Samacheer Kalvi') {
    return getTNStudyPlan(goals, subject);
  }

  return `# Personalized Study Plan
**Subject:** ${subject} | **Curriculum:** ${curriculum}
**Goal:** ${goals}

## 8-Week Study Plan

### Week 1–2: Foundation Building
- **Monday/Wednesday/Friday:** Core concept review (45 min each)
- **Tuesday/Thursday:** Practice problems (30 min each)
- **Weekend:** Review and consolidate (1 hour)
- Focus: Chapters 1–3, basic terminology

### Week 3–4: Core Development
- **Daily:** Topic-specific study (1 hour)
- **Weekend:** Past paper practice (2 hours)
- Focus: Main theories and applications

### Week 5–6: Advanced Topics
- **Daily:** Complex problem solving (1 hour)
- **Weekend:** Full mock exam (3 hours)
- Focus: Higher-order thinking skills

### Week 7: Intensive Revision
- **Daily:** Targeted weak areas (2 hours)
- Review all previous notes
- Focus: Exam technique and timing

### Week 8: Final Preparation
- **Daily:** Light revision (45 min)
- Rest and mental preparation
- Focus: Confidence building

## Daily Study Tips
✅ Start each session with a 5-minute review of previous material
✅ Use the Pomodoro technique: 25 min study, 5 min break
✅ End each session by writing 3 key takeaways
✅ Stay hydrated and take regular breaks

## Progress Milestones
- [ ] Week 2: Complete foundation topics
- [ ] Week 4: Score 60%+ on practice tests
- [ ] Week 6: Score 75%+ on mock exams
- [ ] Week 8: Achieve target grade

*Generated by Pristine Learning AI Assistant*`;
}

// ─── Tool Components ──────────────────────────────────────────────────────────

function StudyMaterialTool() {
  const [subject, setSubject] = useState('');
  const [curriculum, setCurriculum] = useState('');
  const [result, setResult] = useState('');
  const [loading, setLoading] = useState(false);

  const handleGenerate = () => {
    if (!subject || !curriculum) return;
    setLoading(true);
    setTimeout(() => {
      setResult(generateStudyMaterial(subject, curriculum));
      setLoading(false);
    }, 800);
  };

  return (
    <div className="space-y-4">
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
        <div className="space-y-1">
          <Label>Subject</Label>
          <Input placeholder="e.g. Mathematics, Science…" value={subject} onChange={e => setSubject(e.target.value)} />
        </div>
        <div className="space-y-1">
          <Label>Curriculum</Label>
          <Select value={curriculum} onValueChange={setCurriculum}>
            <SelectTrigger><SelectValue placeholder="Select curriculum" /></SelectTrigger>
            <SelectContent>
              {CURRICULA.map(c => <SelectItem key={c} value={c}>{c}</SelectItem>)}
            </SelectContent>
          </Select>
        </div>
      </div>
      <Button onClick={handleGenerate} disabled={!subject || !curriculum || loading} className="btn-primary gap-2">
        <Sparkles className="w-4 h-4" />
        {loading ? 'Generating…' : 'Generate Study Material'}
      </Button>
      {result && (
        <div className="bg-muted/30 rounded-xl p-5 border border-border">
          <pre className="whitespace-pre-wrap text-sm font-sans leading-relaxed">{result}</pre>
        </div>
      )}
    </div>
  );
}

function QuizTool() {
  const [topic, setTopic] = useState('');
  const [curriculum, setCurriculum] = useState('');
  const [questions, setQuestions] = useState<Array<{ question: string; options: string[]; answer: number }>>([]);
  const [selected, setSelected] = useState<Record<number, number>>({});
  const [submitted, setSubmitted] = useState(false);
  const [loading, setLoading] = useState(false);

  const handleGenerate = () => {
    if (!topic || !curriculum) return;
    setLoading(true);
    setSelected({});
    setSubmitted(false);
    setTimeout(() => {
      setQuestions(generateQuiz(topic, curriculum));
      setLoading(false);
    }, 600);
  };

  const score = submitted
    ? questions.filter((q, i) => selected[i] === q.answer).length
    : 0;

  return (
    <div className="space-y-4">
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
        <div className="space-y-1">
          <Label>Topic</Label>
          <Input placeholder="e.g. Mathematics, Science, Social Science…" value={topic} onChange={e => setTopic(e.target.value)} />
        </div>
        <div className="space-y-1">
          <Label>Curriculum</Label>
          <Select value={curriculum} onValueChange={setCurriculum}>
            <SelectTrigger><SelectValue placeholder="Select curriculum" /></SelectTrigger>
            <SelectContent>
              {CURRICULA.map(c => <SelectItem key={c} value={c}>{c}</SelectItem>)}
            </SelectContent>
          </Select>
        </div>
      </div>
      <Button onClick={handleGenerate} disabled={!topic || !curriculum || loading} className="btn-primary gap-2">
        <HelpCircle className="w-4 h-4" />
        {loading ? 'Generating…' : 'Generate Quiz'}
      </Button>

      {questions.length > 0 && (
        <div className="space-y-4">
          {submitted && (
            <div className={`p-4 rounded-xl border ${score >= 4 ? 'bg-green-50 border-green-200' : 'bg-amber-50 border-amber-200'}`}>
              <p className="font-semibold">Score: {score}/{questions.length}</p>
              <p className="text-sm text-muted-foreground">
                {score >= 4 ? '🎉 Excellent work!' : score >= 3 ? '👍 Good effort!' : '📚 Keep studying!'}
              </p>
            </div>
          )}
          {questions.map((q, qi) => (
            <div key={qi} className="bg-white rounded-xl border border-border p-4">
              <p className="font-medium text-sm mb-3">{qi + 1}. {q.question}</p>
              <div className="space-y-2">
                {q.options.map((opt, oi) => (
                  <button
                    key={oi}
                    onClick={() => !submitted && setSelected(prev => ({ ...prev, [qi]: oi }))}
                    className={`w-full text-left px-3 py-2 rounded-lg border text-sm transition-all ${
                      submitted
                        ? oi === q.answer
                          ? 'bg-green-50 border-green-400 text-green-700'
                          : selected[qi] === oi
                          ? 'bg-red-50 border-red-300 text-red-600'
                          : 'border-border'
                        : selected[qi] === oi
                        ? 'border-primary bg-primary/5 text-primary'
                        : 'border-border hover:border-primary/40'
                    }`}
                  >
                    {String.fromCharCode(65 + oi)}. {opt}
                  </button>
                ))}
              </div>
            </div>
          ))}
          {!submitted && (
            <Button
              onClick={() => setSubmitted(true)}
              disabled={Object.keys(selected).length < questions.length}
              className="btn-primary"
            >
              Submit Answers
            </Button>
          )}
          {submitted && (
            <Button variant="outline" onClick={() => { setSubmitted(false); setSelected({}); setQuestions([]); }}>
              Try Another Quiz
            </Button>
          )}
        </div>
      )}
    </div>
  );
}

function NoteSummarizerTool() {
  const [notes, setNotes] = useState('');
  const [summary, setSummary] = useState('');
  const [loading, setLoading] = useState(false);

  const handleSummarize = () => {
    if (!notes.trim()) return;
    setLoading(true);
    setTimeout(() => {
      setSummary(summarizeNotes(notes));
      setLoading(false);
    }, 600);
  };

  return (
    <div className="space-y-4">
      <div className="space-y-1">
        <Label>Paste Your Notes</Label>
        <Textarea
          placeholder="Paste your notes here to get a concise summary…"
          value={notes}
          onChange={e => setNotes(e.target.value)}
          rows={8}
          className="font-mono text-sm"
        />
        <p className="text-xs text-muted-foreground">{notes.split(' ').filter(Boolean).length} words</p>
      </div>
      <Button onClick={handleSummarize} disabled={!notes.trim() || loading} className="btn-primary gap-2">
        <FileText className="w-4 h-4" />
        {loading ? 'Summarizing…' : 'Summarize Notes'}
      </Button>
      {summary && (
        <div className="bg-muted/30 rounded-xl p-5 border border-border">
          <pre className="whitespace-pre-wrap text-sm font-sans leading-relaxed">{summary}</pre>
        </div>
      )}
    </div>
  );
}

function StudyPlanTool() {
  const [goals, setGoals] = useState('');
  const [subject, setSubject] = useState('');
  const [curriculum, setCurriculum] = useState('');
  const [plan, setPlan] = useState('');
  const [loading, setLoading] = useState(false);

  const handleGenerate = () => {
    if (!goals || !subject || !curriculum) return;
    setLoading(true);
    setTimeout(() => {
      setPlan(generateStudyPlan(goals, subject, curriculum));
      setLoading(false);
    }, 800);
  };

  return (
    <div className="space-y-4">
      <div className="space-y-1">
        <Label>Your Goals</Label>
        <Input
          placeholder="e.g. Score 90%+ in Samacheer Kalvi Class 10 Maths public exam"
          value={goals}
          onChange={e => setGoals(e.target.value)}
        />
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
        <div className="space-y-1">
          <Label>Subject</Label>
          <Input placeholder="e.g. Mathematics, Science…" value={subject} onChange={e => setSubject(e.target.value)} />
        </div>
        <div className="space-y-1">
          <Label>Curriculum</Label>
          <Select value={curriculum} onValueChange={setCurriculum}>
            <SelectTrigger><SelectValue placeholder="Select curriculum" /></SelectTrigger>
            <SelectContent>
              {CURRICULA.map(c => <SelectItem key={c} value={c}>{c}</SelectItem>)}
            </SelectContent>
          </Select>
        </div>
      </div>
      <Button onClick={handleGenerate} disabled={!goals || !subject || !curriculum || loading} className="btn-primary gap-2">
        <Calendar className="w-4 h-4" />
        {loading ? 'Generating…' : 'Generate Study Plan'}
      </Button>
      {plan && (
        <div className="bg-muted/30 rounded-xl p-5 border border-border">
          <pre className="whitespace-pre-wrap text-sm font-sans leading-relaxed">{plan}</pre>
        </div>
      )}
    </div>
  );
}

// ─── Main Page ────────────────────────────────────────────────────────────────

export default function AIStudyAssistantPage() {
  const { identity } = useInternetIdentity();
  const navigate = useNavigate();

  if (!identity) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background">
        <div className="text-center">
          <h2 className="font-display text-2xl font-bold mb-3">Login Required</h2>
          <Button onClick={() => navigate({ to: '/' })} className="btn-primary">Go to Homepage</Button>
        </div>
      </div>
    );
  }

  return (
    <DashboardLayout role="student">
      <div className="p-6 space-y-6 animate-fade-in">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 bg-primary/10 rounded-xl flex items-center justify-center">
            <Brain className="w-6 h-6 text-primary" />
          </div>
          <div>
            <h1 className="font-display text-2xl font-bold">AI Study Assistant</h1>
            <p className="text-muted-foreground text-sm">Powered by intelligent content generation for all major curricula</p>
          </div>
        </div>

        <div className="flex flex-wrap gap-2">
          {CURRICULA.map(c => (
            <Badge
              key={c}
              variant={c === 'Tamil Nadu Samacheer Kalvi' ? 'default' : 'secondary'}
              className="text-xs"
            >
              {c === 'Tamil Nadu Samacheer Kalvi' ? '🏫 ' + c : c}
            </Badge>
          ))}
        </div>

        <Tabs defaultValue="materials">
          <TabsList className="flex-wrap h-auto gap-1">
            <TabsTrigger value="materials" className="gap-1.5">
              <BookOpen className="w-3.5 h-3.5" /> Study Materials
            </TabsTrigger>
            <TabsTrigger value="quiz" className="gap-1.5">
              <HelpCircle className="w-3.5 h-3.5" /> Quiz Creator
            </TabsTrigger>
            <TabsTrigger value="summarize" className="gap-1.5">
              <FileText className="w-3.5 h-3.5" /> Note Summarizer
            </TabsTrigger>
            <TabsTrigger value="plan" className="gap-1.5">
              <Calendar className="w-3.5 h-3.5" /> Study Plan
            </TabsTrigger>
          </TabsList>

          <TabsContent value="materials" className="mt-4">
            <div className="bg-white rounded-xl border border-border p-6">
              <h2 className="font-semibold mb-1">Study Material Generator</h2>
              <p className="text-sm text-muted-foreground mb-4">
                Generate comprehensive study notes for any subject and curriculum — including Tamil Nadu Samacheer Kalvi.
              </p>
              <StudyMaterialTool />
            </div>
          </TabsContent>

          <TabsContent value="quiz" className="mt-4">
            <div className="bg-white rounded-xl border border-border p-6">
              <h2 className="font-semibold mb-1">Quiz Creator</h2>
              <p className="text-sm text-muted-foreground mb-4">
                Generate multiple-choice quizzes tailored to your curriculum — with dedicated Samacheer Kalvi question sets for Maths, Science, Social Science, and English.
              </p>
              <QuizTool />
            </div>
          </TabsContent>

          <TabsContent value="summarize" className="mt-4">
            <div className="bg-white rounded-xl border border-border p-6">
              <h2 className="font-semibold mb-1">Note Summarizer</h2>
              <p className="text-sm text-muted-foreground mb-4">
                Paste your notes and get a concise, structured summary with key points highlighted.
              </p>
              <NoteSummarizerTool />
            </div>
          </TabsContent>

          <TabsContent value="plan" className="mt-4">
            <div className="bg-white rounded-xl border border-border p-6">
              <h2 className="font-semibold mb-1">Personalized Study Plan</h2>
              <p className="text-sm text-muted-foreground mb-4">
                Get a custom 8-week study plan aligned to your curriculum — with a dedicated Tamil Nadu Samacheer Kalvi schedule and exam strategy.
              </p>
              <StudyPlanTool />
            </div>
          </TabsContent>
        </Tabs>
      </div>
    </DashboardLayout>
  );
}
