/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const TeacherProfile = IDL.Record({
  'availabilitySlots' : IDL.Vec(IDL.Text),
  'subjects' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'hourlyRate' : IDL.Nat,
  'languages' : IDL.Vec(IDL.Text),
  'ratings' : IDL.Float64,
  'photoUrl' : IDL.Text,
  'qualifications' : IDL.Text,
  'experience' : IDL.Text,
  'demoVideoUrl' : IDL.Text,
  'reviewCount' : IDL.Nat,
});
export const WeeklySnapshot = IDL.Record({
  'newSubscriptions' : IDL.Nat,
  'messagesSent' : IDL.Nat,
  'commissionEarned' : IDL.Nat,
  'newTeachers' : IDL.Nat,
  'sessionsBooked' : IDL.Nat,
  'weekIdentifier' : IDL.Text,
  'sessionsCompleted' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
  'newUsers' : IDL.Nat,
  'reviewsSubmitted' : IDL.Nat,
});
export const ActivityLog = IDL.Record({
  'metadata' : IDL.Text,
  'userId' : IDL.Principal,
  'actionType' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const PerformanceMetrics = IDL.Record({
  'completedSessions' : IDL.Nat,
  'withdrawalHistory' : IDL.Vec(IDL.Nat),
  'activeSubscription' : IDL.Text,
  'reviewsGiven' : IDL.Nat,
  'averageRating' : IDL.Float64,
  'earnings' : IDL.Nat,
  'cancelledSessions' : IDL.Nat,
  'totalReviews' : IDL.Nat,
  'totalSessions' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'referralCode' : IDL.Opt(IDL.Text),
  'role' : UserRole,
  'fullName' : IDL.Text,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'registrationTime' : IDL.Int,
});
export const PlatformConfig = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'commissionRateBps' : IDL.Nat,
  'stripeSecretKey' : IDL.Text,
});
export const RazorpayConfig = IDL.Record({
  'keyId' : IDL.Text,
  'keySecret' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminDeleteBooking' : IDL.Func([IDL.Text], [], []),
  'adminDeleteMessage' : IDL.Func([IDL.Text], [], []),
  'adminDeleteReview' : IDL.Func([IDL.Text], [], []),
  'adminUpdateBookingStatus' : IDL.Func([IDL.Text, BookingStatus], [], []),
  'approveWithdrawal' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createTeacherProfile' : IDL.Func([IDL.Text, TeacherProfile], [], []),
  'createWeeklySnapshot' : IDL.Func([WeeklySnapshot], [], []),
  'deleteUser' : IDL.Func([IDL.Principal], [], []),
  'getActivityLogsByActionType' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ActivityLog)],
      ['query'],
    ),
  'getActivityLogsByDateRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(ActivityLog)],
      ['query'],
    ),
  'getActivityLogsByUserId' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ActivityLog)],
      ['query'],
    ),
  'getAllActivityLogs' : IDL.Func([], [IDL.Vec(ActivityLog)], ['query']),
  'getAllPerformanceMetrics' : IDL.Func(
      [],
      [IDL.Vec(PerformanceMetrics)],
      ['query'],
    ),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDemoAdminProfile' : IDL.Func([], [UserProfile], ['query']),
  'getPerformanceMetrics' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PerformanceMetrics)],
      ['query'],
    ),
  'getPlatformConfig' : IDL.Func([], [PlatformConfig], ['query']),
  'getRazorpayConfig' : IDL.Func([], [IDL.Opt(RazorpayConfig)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTeacherProfile' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(TeacherProfile)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWeeklySnapshot' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(WeeklySnapshot)],
      ['query'],
    ),
  'getWeeklySnapshots' : IDL.Func([], [IDL.Vec(WeeklySnapshot)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listTeacherProfiles' : IDL.Func([], [IDL.Vec(TeacherProfile)], ['query']),
  'logActivity' : IDL.Func([ActivityLog], [], []),
  'registerUser' : IDL.Func([UserProfile], [], []),
  'rejectWithdrawal' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setPlatformCommissionRate' : IDL.Func([IDL.Nat], [], []),
  'setRazorpayConfig' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setStripeConfig' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'setUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updatePerformanceMetrics' : IDL.Func(
      [IDL.Principal, PerformanceMetrics],
      [],
      [],
    ),
  'updateTeacherProfile' : IDL.Func([IDL.Text, TeacherProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const TeacherProfile = IDL.Record({
    'availabilitySlots' : IDL.Vec(IDL.Text),
    'subjects' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'hourlyRate' : IDL.Nat,
    'languages' : IDL.Vec(IDL.Text),
    'ratings' : IDL.Float64,
    'photoUrl' : IDL.Text,
    'qualifications' : IDL.Text,
    'experience' : IDL.Text,
    'demoVideoUrl' : IDL.Text,
    'reviewCount' : IDL.Nat,
  });
  const WeeklySnapshot = IDL.Record({
    'newSubscriptions' : IDL.Nat,
    'messagesSent' : IDL.Nat,
    'commissionEarned' : IDL.Nat,
    'newTeachers' : IDL.Nat,
    'sessionsBooked' : IDL.Nat,
    'weekIdentifier' : IDL.Text,
    'sessionsCompleted' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
    'newUsers' : IDL.Nat,
    'reviewsSubmitted' : IDL.Nat,
  });
  const ActivityLog = IDL.Record({
    'metadata' : IDL.Text,
    'userId' : IDL.Principal,
    'actionType' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const PerformanceMetrics = IDL.Record({
    'completedSessions' : IDL.Nat,
    'withdrawalHistory' : IDL.Vec(IDL.Nat),
    'activeSubscription' : IDL.Text,
    'reviewsGiven' : IDL.Nat,
    'averageRating' : IDL.Float64,
    'earnings' : IDL.Nat,
    'cancelledSessions' : IDL.Nat,
    'totalReviews' : IDL.Nat,
    'totalSessions' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'referralCode' : IDL.Opt(IDL.Text),
    'role' : UserRole,
    'fullName' : IDL.Text,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'registrationTime' : IDL.Int,
  });
  const PlatformConfig = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'commissionRateBps' : IDL.Nat,
    'stripeSecretKey' : IDL.Text,
  });
  const RazorpayConfig = IDL.Record({
    'keyId' : IDL.Text,
    'keySecret' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminDeleteBooking' : IDL.Func([IDL.Text], [], []),
    'adminDeleteMessage' : IDL.Func([IDL.Text], [], []),
    'adminDeleteReview' : IDL.Func([IDL.Text], [], []),
    'adminUpdateBookingStatus' : IDL.Func([IDL.Text, BookingStatus], [], []),
    'approveWithdrawal' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createTeacherProfile' : IDL.Func([IDL.Text, TeacherProfile], [], []),
    'createWeeklySnapshot' : IDL.Func([WeeklySnapshot], [], []),
    'deleteUser' : IDL.Func([IDL.Principal], [], []),
    'getActivityLogsByActionType' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ActivityLog)],
        ['query'],
      ),
    'getActivityLogsByDateRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(ActivityLog)],
        ['query'],
      ),
    'getActivityLogsByUserId' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ActivityLog)],
        ['query'],
      ),
    'getAllActivityLogs' : IDL.Func([], [IDL.Vec(ActivityLog)], ['query']),
    'getAllPerformanceMetrics' : IDL.Func(
        [],
        [IDL.Vec(PerformanceMetrics)],
        ['query'],
      ),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDemoAdminProfile' : IDL.Func([], [UserProfile], ['query']),
    'getPerformanceMetrics' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PerformanceMetrics)],
        ['query'],
      ),
    'getPlatformConfig' : IDL.Func([], [PlatformConfig], ['query']),
    'getRazorpayConfig' : IDL.Func([], [IDL.Opt(RazorpayConfig)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTeacherProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(TeacherProfile)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWeeklySnapshot' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(WeeklySnapshot)],
        ['query'],
      ),
    'getWeeklySnapshots' : IDL.Func([], [IDL.Vec(WeeklySnapshot)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listTeacherProfiles' : IDL.Func([], [IDL.Vec(TeacherProfile)], ['query']),
    'logActivity' : IDL.Func([ActivityLog], [], []),
    'registerUser' : IDL.Func([UserProfile], [], []),
    'rejectWithdrawal' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setPlatformCommissionRate' : IDL.Func([IDL.Nat], [], []),
    'setRazorpayConfig' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setStripeConfig' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'setUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updatePerformanceMetrics' : IDL.Func(
        [IDL.Principal, PerformanceMetrics],
        [],
        [],
      ),
    'updateTeacherProfile' : IDL.Func([IDL.Text, TeacherProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };